version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto-17
    commands:
      - echo Installing Maven
      - mvn --version
  build: 
    commands:
      - echo Starting build...
      - cd todo
      - mvn -B package