version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven
      - mvn --version
  build:
    commands:
      - echo Starting Maven build
      - pwd
      - ls -la
      - cd todo
      - pwd
      - ls -la
      - mvn -B package
artifacts:
  files:
    - todo/target/*.jar
